servers=[
	{
		:hostname => 'vm1',
		:ip => '192.168.122.2',
		:box => 'ubuntu/bionic64',
		:ram => 512,
		:cpu => 1,
		:disk => '20GB'
	},
	{
		:hostname => 'vm2',
		:ip => '192.168.122.3',
		:box => 'ubuntu/bionic64',
		:ram => 512,
		:cpu => 1,
		:disk => '30GB'
	},
	{
		:hostname => 'vm3',
		:ip => '192.168.122.4',
		:box => 'ubuntu/bionic64',
		:ram => 512,
		:cpu => 1,
		:disk => '15GB'
	},
	{
		:hostname => 'vm4',
		:ip => '192.168.122.5',
		:box => 'ubuntu/bionic64',
		:ram => 512,
		:cpu => 1,
		:disk => '15GB'
	},
	{
		:hostname => 'vm5',
		:ip => '192.168.122.6',
		:box => 'ubuntu/bionic64',
		:ram => 512,
		:cpu => 1,
		:disk => '15GB'
	},
	{
		:hostname => 'vm6',
		:ip => '192.168.122.7',
		:box => 'ubuntu/bionic64',
		:ram => 512,
		:cpu => 1,
		:disk => '15GB'
	},
	{
		:hostname => 'vm7',
		:ip => '192.168.122.8',
		:box => 'ubuntu/bionic64',
		:ram => 512,
		:cpu => 1,
		:disk => '15GB'
	},
	{
		:hostname => 'vm8',
		:ip => '192.168.122.9',
		:box => 'ubuntu/bionic64',
		:ram => 512,
		:cpu => 1,
		:disk => '15GB'
	},
	{
		:hostname => 'vm9',
		:ip => '192.168.122.10',
		:box => 'ubuntu/bionic64',
		:ram => 512,
		:cpu => 1,
		:disk => '15GB'
	},
	{
		:hostname => 'vm10',
		:ip => '192.168.122.11',
		:box => 'ubuntu/bionic64',
		:ram => 512,
		:cpu => 1,
		:disk => '15GB'
	}
]


agent_path='D:/BUET/Data Management In the Cloud/Project/COSCO/framework/agent'

Vagrant.configure(2) do |config|
    servers.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.box = machine[:box]
            node.vm.disk :disk, size: machine[:disk], primary: true
            config.ssh.insert_key = false
            config.vm.boot_timeout = 800
            # Configure SSH keys
            config.ssh.private_key_path = ["~/.ssh/id_rsa", "~/.vagrant.d/insecure_private_key"]
            config.vm.provision "pub key", type: "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
            config.vm.provision "pri key", type:  "file", source: "~/.ssh/id_rsa", destination: "$HOME/agent/"
            config.vm.provision "pri key chmod", type:  "shell", inline: "sudo chmod 600 $HOME/agent/id_rsa", privileged: false
            # Transfer agent data
            config.vm.provision "data transfer", type:  "file", source: agent_path, destination: "$HOME/"
            # Agent setup
            config.vm.provision "calIPS script chmod", type:  "shell", inline: "sudo chmod +x $HOME/agent/scripts/calIPS.sh", privileged: false
            config.vm.provision "calIPS2 script chmod", type:  "shell", inline: "sudo chmod +x $HOME/agent/scripts/calIPS_clock.sh", privileged: false
            config.vm.provision "set script chmod", type:  "shell", inline: "sudo chmod +x $HOME/agent/scripts/setup.sh", privileged: false
            config.vm.provision "conf setup script", type:  "shell", inline: "sed -i -e 's/\r$//' $HOME/agent/scripts/setup.sh", privileged: false
            config.vm.provision "run setup script", type:  "shell", inline: "$HOME/agent/scripts/setup.sh", privileged: false
            # Configure agent
            node.vm.hostname = machine[:hostname]
            node.vm.network :private_network, ip: machine[:ip]
            node.vm.provider "virtualbox" do |vb|
            	vb.name = machine[:hostname]
            	vb.cpus = machine[:cpu]
                vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
            end
        end
    end
end